{% set name = "deepecho" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepecho-{{ version }}.tar.gz
  sha256: 49afaf8305cd695f8f6dbc7969ada55c81a3048e2928712422bed98f6fbd4282

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - python >=3.8,<3.12
    - pytorch >=1.8.0
    - tqdm >=4.15,<5

test:
  imports:
    - deepecho
    - deepecho.models
  commands:
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/unit

about:
  home: https://github.com/sdv-dev/DeepEcho
  summary: Mixed-type multivariate time series modeling with generative adversarial networks.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
