{% set name = "deepecho" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deepecho-{{ version }}.tar.gz
  sha256: b2bc4b49f067ccc9c13fbfd95035e7babcf1c17800720ee7f45183bde4a663b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
  run:
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - python >={{ python_min }},<3.14
    - pytorch >=1.9.0
    - tqdm >=4.29,<5

test:
  imports:
    - deepecho
    - deepecho.models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/sdv-dev/DeepEcho
  summary: Mixed-type multivariate time series modeling with generative adversarial networks.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
