{% set name = "deepecho" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepecho-{{ version }}.tar.gz
  sha256: c49baee281691f220b880b17fe095134c797dfb90bdb2b2d8b783da69386b51c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.11
  run:
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - python >=3.7,<3.11
    - pytorch >=1.4,<2
    - tqdm >=4.15,<5

test:
  imports:
    - deepecho
    - deepecho.models
  commands:
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/unit

about:
  home: https://github.com/sdv-dev/DeepEcho
  summary: Mixed-type multivariate time series modeling with generative adversarial networks.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
